#!/usr/bin/env python

import socket
import argparse

def get_ip(hostname):
    return socket.gethostbyname(hostname)

if __name__ == "__main__":

    parser = argparse.ArgumentParser(prog="resolve", \
                                     description="Resolve a DNS name to an IP")
    parser.add_argument("dnsname")
    args = parser.parse_args()
    print get_ip(args.dnsname)
